In [29]:
import numpy as np

Problem Statement 1: 
Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [30]:
def vanderFunction(arr, N=0):
    if N == 0:
        N = len(arr)
    mat = np.zeros((len(arr), N))
    for i in range(len(arr)):
        for j in range(0, N):
            mat[i, j] = arr[i]**(N-j-1)
    return mat
vanderMatrix = vanderFunction(np.array([1, 2, 3, 5]), 3)
print(vanderMatrix)

[[ 1.  1.  1.]
 [ 4.  2.  1.]
 [ 9.  3.  1.]
 [25.  5.  1.]]


Problem Statement 2: Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [31]:
arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
def findMovingAverage(arr, window):
    return [np.array(arr[i:i+window]).mean() for i in range(len(arr)-(window-1))]
movingAverage = findMovingAverage(arr, 3)
print('Moving Average Sequence is: {}'.format(movingAverage))

Moving Average Sequence is: [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
